# Generated by Django 3.0.8 on 2020-07-09 19:35

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Follower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=128)),
                ('usernames', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=128)),
                ('usernames', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=128)),
                ('usernames', django_mysql.models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('radius', models.PositiveIntegerField()),
                ('gpsCoordinate', django_mysql.models.JSONField(default=dict)),
                ('isGpsExact', models.BooleanField()),
                ('isPostPublic', models.BooleanField()),
                ('category', models.CharField(max_length=128)),
                ('expirationHours', models.PositiveIntegerField()),
                ('creationTime', models.DateTimeField()),
                ('message', models.TextField()),
            ],
        ),
    ]
