# Generated by Django 3.0.8 on 2020-07-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('me', models.CharField(max_length=128)),
                ('who', models.CharField(max_length=128)),
            ],
        ),
        migrations.RenameField(
            model_name='follower',
            old_name='who',
            new_name='me',
        ),
        migrations.RenameField(
            model_name='following',
            old_name='who',
            new_name='me',
        ),
        migrations.RenameField(
            model_name='requests',
            old_name='who',
            new_name='me',
        ),
    ]
